version: "3.9"

services:
  # MAIN REPO
  repo:
    image: postgres:15.1-alpine3.17
    restart: always
    container_name: ${APP_NAME}_repo
    ports:
      - ${DB_EXPOSE_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - repo_data:/var/lib/postgresql/data
    networks:
      - mylib
  # TOKEN REPO
  session:
    image: redis:alpine3.17
    container_name: ${APP_NAME}_session
    restart: unless-stopped
    command: redis-server --requirepass ${SESSION_PASSWORD}
    ports:
      - ${SESSION_EXPOSE_PORT}:${SESSION_PORT}
    environment:
      - REDIS_MASTER_HOST=${SESSION_HOST}
      - REDIS_PASSWORD=${SESSION_PASSWORD}
      - REDIS_PORT_NUMBER=${SESSION_PORT}
    volumes:
      - session_data:/data
    networks:
      - mylib
  # API
  api:
    build: .
    container_name: ${APP_NAME}_rest_api
    privileged: true
    ports:
      - ${SRV_PORT}:${SRV_PORT}
    depends_on:
      - repo
      - session
    networks:
      - mylib

volumes:
  repo_data:
  session_data:

networks:
  mylib:
    driver: bridge