openapi: 3.0.0


info:
paths:
  /readers:
  /books:

components:
  securitySchemes:
    bearerAuth:
      type: https
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]